version: "3"
services:

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    restart: always
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=eu-west-1
      - DOCKER_HOST=unix:///var/run/docker.sock
    healthcheck:
      test: ["CMD", "bash", "-c", "awslocal s3 ls bucket"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - 4566:4566
      - 4571:4571
      - 4572:4572
      - 9999:8080
    volumes:
      - ./aws:/docker-entrypoint-initaws.d

  task_runner:
    build: .
    container_name: task_runner
    environment:
      - S3_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=foo
      - AWS_SECRET_ACCESS_KEY=bar
      - AWS_REGION=eu-west-1
    depends_on:
      localstack:
        condition: service_healthy